//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.15 at 09:07:47 PM CEST 
//


package com.ftn_booking.agentendpoint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseWrapper" type="{http://ftn-booking.com/agentEndpoint}ResponseWrapperLong"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseWrapper"
})
@XmlRootElement(name = "manageMonthlyPricesResponse")
public class ManageMonthlyPricesResponse {

    @XmlElement(required = true)
    protected ResponseWrapperLong responseWrapper;

    /**
     * Gets the value of the responseWrapper property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseWrapperLong }
     *     
     */
    public ResponseWrapperLong getResponseWrapper() {
        return responseWrapper;
    }

    /**
     * Sets the value of the responseWrapper property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseWrapperLong }
     *     
     */
    public void setResponseWrapper(ResponseWrapperLong value) {
        this.responseWrapper = value;
    }

}
