//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 03:17:15 AM CEST 
//


package com.ftn_booking.agentendpoint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="senderAgentMainServerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="receiverUserMainServerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "senderAgentMainServerId",
    "receiverUserMainServerId",
    "content"
})
public class Message {

    protected long senderAgentMainServerId;
    protected long receiverUserMainServerId;
    @XmlElement(required = true)
    protected String content;

    /**
     * Gets the value of the senderAgentMainServerId property.
     * 
     */
    public long getSenderAgentMainServerId() {
        return senderAgentMainServerId;
    }

    /**
     * Sets the value of the senderAgentMainServerId property.
     * 
     */
    public void setSenderAgentMainServerId(long value) {
        this.senderAgentMainServerId = value;
    }

    /**
     * Gets the value of the receiverUserMainServerId property.
     * 
     */
    public long getReceiverUserMainServerId() {
        return receiverUserMainServerId;
    }

    /**
     * Sets the value of the receiverUserMainServerId property.
     * 
     */
    public void setReceiverUserMainServerId(long value) {
        this.receiverUserMainServerId = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

}
