//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 03:56:30 PM CEST 
//


package com.ftn_booking.agentendpoint;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn_booking.agentendpoint package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn_booking.agentendpoint
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddBookingUnitRequest }
     * 
     */
    public AddBookingUnitRequest createAddBookingUnitRequest() {
        return new AddBookingUnitRequest();
    }

    /**
     * Create an instance of {@link BookingUnit }
     * 
     */
    public BookingUnit createBookingUnit() {
        return new BookingUnit();
    }

    /**
     * Create an instance of {@link CancelReservationResponse }
     * 
     */
    public CancelReservationResponse createCancelReservationResponse() {
        return new CancelReservationResponse();
    }

    /**
     * Create an instance of {@link ResponseWrapper }
     * 
     */
    public ResponseWrapper createResponseWrapper() {
        return new ResponseWrapper();
    }

    /**
     * Create an instance of {@link AddLocalReservationRequest }
     * 
     */
    public AddLocalReservationRequest createAddLocalReservationRequest() {
        return new AddLocalReservationRequest();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link SendMessageRequest }
     * 
     */
    public SendMessageRequest createSendMessageRequest() {
        return new SendMessageRequest();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ConfirmReservationRequest }
     * 
     */
    public ConfirmReservationRequest createConfirmReservationRequest() {
        return new ConfirmReservationRequest();
    }

    /**
     * Create an instance of {@link ReservationLite }
     * 
     */
    public ReservationLite createReservationLite() {
        return new ReservationLite();
    }

    /**
     * Create an instance of {@link AddLocalReservationResponse }
     * 
     */
    public AddLocalReservationResponse createAddLocalReservationResponse() {
        return new AddLocalReservationResponse();
    }

    /**
     * Create an instance of {@link ConfirmReservationResponse }
     * 
     */
    public ConfirmReservationResponse createConfirmReservationResponse() {
        return new ConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link ManageMonthlyPricesResponse }
     * 
     */
    public ManageMonthlyPricesResponse createManageMonthlyPricesResponse() {
        return new ManageMonthlyPricesResponse();
    }

    /**
     * Create an instance of {@link AddBookingUnitResponse }
     * 
     */
    public AddBookingUnitResponse createAddBookingUnitResponse() {
        return new AddBookingUnitResponse();
    }

    /**
     * Create an instance of {@link CancelReservationRequest }
     * 
     */
    public CancelReservationRequest createCancelReservationRequest() {
        return new CancelReservationRequest();
    }

    /**
     * Create an instance of {@link AgentLoginRequest }
     * 
     */
    public AgentLoginRequest createAgentLoginRequest() {
        return new AgentLoginRequest();
    }

    /**
     * Create an instance of {@link ManageMonthlyPricesRequest }
     * 
     */
    public ManageMonthlyPricesRequest createManageMonthlyPricesRequest() {
        return new ManageMonthlyPricesRequest();
    }

    /**
     * Create an instance of {@link MonthlyPrices }
     * 
     */
    public MonthlyPrices createMonthlyPrices() {
        return new MonthlyPrices();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link AgentLoginResponse }
     * 
     */
    public AgentLoginResponse createAgentLoginResponse() {
        return new AgentLoginResponse();
    }

    /**
     * Create an instance of {@link AccomodationType }
     * 
     */
    public AccomodationType createAccomodationType() {
        return new AccomodationType();
    }

    /**
     * Create an instance of {@link HMapStringStringElement }
     * 
     */
    public HMapStringStringElement createHMapStringStringElement() {
        return new HMapStringStringElement();
    }

    /**
     * Create an instance of {@link AccomodationCategory }
     * 
     */
    public AccomodationCategory createAccomodationCategory() {
        return new AccomodationCategory();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link MainServerReservation }
     * 
     */
    public MainServerReservation createMainServerReservation() {
        return new MainServerReservation();
    }

    /**
     * Create an instance of {@link SinchronizationObject }
     * 
     */
    public SinchronizationObject createSinchronizationObject() {
        return new SinchronizationObject();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link BonusFeature }
     * 
     */
    public BonusFeature createBonusFeature() {
        return new BonusFeature();
    }

    /**
     * Create an instance of {@link RegUsrMessage }
     * 
     */
    public RegUsrMessage createRegUsrMessage() {
        return new RegUsrMessage();
    }

    /**
     * Create an instance of {@link RegisteredUserInfo }
     * 
     */
    public RegisteredUserInfo createRegisteredUserInfo() {
        return new RegisteredUserInfo();
    }

}
