//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 03:58:24 PM CEST 
//


package com.ftn_booking.agentendpoint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegUsrMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegUsrMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mainServerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regUsrInfo" type="{http://ftn-booking.com/agentEndpoint}RegisteredUserInfo"/>
 *         &lt;element name="agentUserMainServerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegUsrMessage", propOrder = {
    "mainServerId",
    "content",
    "regUsrInfo",
    "agentUserMainServerId"
})
public class RegUsrMessage {

    protected long mainServerId;
    @XmlElement(required = true)
    protected String content;
    @XmlElement(required = true)
    protected RegisteredUserInfo regUsrInfo;
    protected long agentUserMainServerId;

    /**
     * Gets the value of the mainServerId property.
     * 
     */
    public long getMainServerId() {
        return mainServerId;
    }

    /**
     * Sets the value of the mainServerId property.
     * 
     */
    public void setMainServerId(long value) {
        this.mainServerId = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the regUsrInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RegisteredUserInfo }
     *     
     */
    public RegisteredUserInfo getRegUsrInfo() {
        return regUsrInfo;
    }

    /**
     * Sets the value of the regUsrInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisteredUserInfo }
     *     
     */
    public void setRegUsrInfo(RegisteredUserInfo value) {
        this.regUsrInfo = value;
    }

    /**
     * Gets the value of the agentUserMainServerId property.
     * 
     */
    public long getAgentUserMainServerId() {
        return agentUserMainServerId;
    }

    /**
     * Sets the value of the agentUserMainServerId property.
     * 
     */
    public void setAgentUserMainServerId(long value) {
        this.agentUserMainServerId = value;
    }

}
